from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from types import SimpleNamespace
from unittest import mock

from lucx_post_configurator.dns_manager import (
    DEFAULT_DNS_PROVIDERS,
    DnsCandidate,
    apply_system_dns,
    build_dns_query,
    detect_system_resolver,
    probe_dns_candidates,
    probe_dns_server,
    read_current_system_dns,
    validate_dns_servers,
    verify_dns_resolution,
)
from lucx_post_configurator.runner import Runner
from lucx_post_configurator.targetfs import TargetFS
from lucx_post_configurator.tui import _change_dns_dialog, _network_menu


class DnsManagerTests(unittest.TestCase):
    def test_build_dns_query_format(self) -> None:
        query = build_dns_query("dns.google", tx_id=0x1234)
        self.assertGreater(len(query), 12)
        # Check transaction ID
        self.assertEqual(query[:2], b"\x12\x34")
        # Check flags (standard query with recursion desired)
        self.assertEqual(query[2:4], b"\x01\x00")
        # Check domain parts encoded
        self.assertIn(b"\x03dns\x06google\x00", query)

    def test_validate_dns_servers(self) -> None:
        self.assertEqual(
            validate_dns_servers(["1.1.1.1", "1.0.0.1"]),
            ["1.1.1.1", "1.0.0.1"],
        )
        self.assertEqual(
            validate_dns_servers(["8.8.8.8", "8.8.8.8"]),
            ["8.8.8.8"],
        )
        with self.assertRaisesRegex(ValueError, "пустым"):
            validate_dns_servers([])
        with self.assertRaisesRegex(ValueError, "Максимальное число"):
            validate_dns_servers(["1.1.1.1", "8.8.8.8", "9.9.9.9", "77.88.8.8"])
        with self.assertRaisesRegex(ValueError, "Некорректный IP-адрес"):
            validate_dns_servers(["invalid.dns.ip"])

    def test_read_current_system_dns(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            fs = TargetFS(tempdir)
            resolv_path = fs.path("/etc/resolv.conf")
            resolv_path.parent.mkdir(parents=True, exist_ok=True)
            resolv_path.write_text(
                "# Generated by resolvconf\n"
                "nameserver 8.8.8.8\n"
                "nameserver 1.1.1.1\n"
                "options edns0\n",
                encoding="utf-8",
            )
            servers = read_current_system_dns(fs)
            self.assertEqual(servers, ["8.8.8.8", "1.1.1.1"])

    def test_apply_system_dns_resolvconf(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            fs = TargetFS(tempdir)
            runner = Runner(dry_run=True)
            # Create resolvconf dir and resolvconf.conf
            fs.path("/etc/resolvconf").mkdir(parents=True, exist_ok=True)
            fs.path("/etc/resolvconf.conf").write_text("resolv_conf=/etc/resolv.conf\n", encoding="utf-8")

            result = apply_system_dns(fs, runner, ["1.1.1.1", "1.0.0.1"])
            self.assertTrue(result["ok"])
            self.assertEqual(result["servers"], ["1.1.1.1", "1.0.0.1"])
            self.assertEqual(result["resolver"], "resolvconf")

            # Verify /etc/resolv.conf
            resolv_content = fs.read_text("/etc/resolv.conf")
            self.assertIn("nameserver 1.1.1.1", resolv_content)
            self.assertIn("nameserver 1.0.0.1", resolv_content)

            # Verify /etc/resolvconf/resolv.conf.d/head
            head_content = fs.read_text("/etc/resolvconf/resolv.conf.d/head")
            self.assertIn("nameserver 1.1.1.1", head_content)

            # Verify /etc/resolvconf.conf
            conf_content = fs.read_text("/etc/resolvconf.conf")
            self.assertIn('name_servers="1.1.1.1 1.0.0.1"', conf_content)

    def test_apply_system_dns_systemd_resolved(self) -> None:
        with tempfile.TemporaryDirectory() as tempdir:
            fs = TargetFS(tempdir)
            runner = Runner(dry_run=True)

            with mock.patch("lucx_post_configurator.dns_manager.detect_system_resolver", return_value="systemd-resolved"):
                result = apply_system_dns(fs, runner, ["9.9.9.9"])
                self.assertTrue(result["ok"])
                self.assertEqual(result["resolver"], "systemd-resolved")

                # Verify /etc/systemd/resolved.conf.d/60-lucx-post-configurator.conf
                conf_path = "/etc/systemd/resolved.conf.d/60-lucx-post-configurator.conf"
                conf_text = fs.read_text(conf_path)
                self.assertIn("DNS=9.9.9.9", conf_text)

    def test_probe_dns_candidates_mocked(self) -> None:
        with mock.patch("lucx_post_configurator.dns_manager.probe_dns_server") as mock_probe:
            mock_probe.side_effect = lambda ip, **_kw: 14.5 if ip == "1.1.1.1" else None
            candidates = probe_dns_candidates(
                providers=[
                    ("Cloudflare", ("1.1.1.1", "1.0.0.1"), "Fast"),
                    ("Offline", ("192.0.2.1",), "Offline"),
                ],
                timeout=0.1,
            )
            self.assertEqual(len(candidates), 2)
            self.assertEqual(candidates[0].name, "Cloudflare")
            self.assertEqual(candidates[0].latency_ms, 14.5)
            self.assertEqual(candidates[1].name, "Offline")
            self.assertIsNone(candidates[1].latency_ms)

    def test_tui_change_dns_dialog_preset(self) -> None:
        mock_candidates = [
            DnsCandidate("Cloudflare", ("1.1.1.1", "1.0.0.1"), "Fast", 12.0),
            DnsCandidate("Google", ("8.8.8.8", "8.8.4.4"), "Global", 15.0),
        ]
        applied: list[list[str]] = []
        engine = SimpleNamespace(
            get_current_system_dns=lambda: ["8.8.8.8"],
            probe_dns_candidates=lambda: mock_candidates,
            set_system_dns=lambda servers: (
                applied.append(servers) or {
                    "ok": True,
                    "servers": servers,
                    "resolver": "resolvconf",
                    "resolution_verified": True,
                }
            ),
        )
        # Inputs: select option 1 (Cloudflare), confirm with 1 (Yes)
        inputs = iter(["1", "1"])
        output: list[str] = []

        _change_dns_dialog(
            engine,  # type: ignore[arg-type]
            input_fn=lambda _prompt: next(inputs),
            output_fn=output.append,
        )

        rendered = "\n".join(output)
        self.assertIn("Смена системного DNS", rendered)
        self.assertIn("Текущий активный DNS: 8.8.8.8", rendered)
        self.assertIn("Cloudflare", rendered)
        self.assertIn("12.0 ms", rendered)
        self.assertIn("Статус: успешно", rendered)
        self.assertIn("подтверждена", rendered)
        self.assertEqual(applied, [["1.1.1.1", "1.0.0.1"]])

    def test_tui_change_dns_dialog_custom(self) -> None:
        mock_candidates = [
            DnsCandidate("Cloudflare", ("1.1.1.1", "1.0.0.1"), "Fast", 12.0),
        ]
        applied: list[list[str]] = []
        engine = SimpleNamespace(
            get_current_system_dns=lambda: ["1.1.1.1"],
            probe_dns_candidates=lambda: mock_candidates,
            set_system_dns=lambda servers: (
                applied.append(servers) or {
                    "ok": True,
                    "servers": servers,
                    "resolver": "resolvconf",
                    "resolution_verified": True,
                }
            ),
        )
        # Inputs: select option 2 (custom), enter IPs, confirm with 1 (Yes)
        inputs = iter(["2", "77.88.8.8, 77.88.8.1", "1"])
        output: list[str] = []

        _change_dns_dialog(
            engine,  # type: ignore[arg-type]
            input_fn=lambda _prompt: next(inputs),
            output_fn=output.append,
        )

        rendered = "\n".join(output)
        self.assertIn("Выбранные DNS-серверы: 77.88.8.8, 77.88.8.1", rendered)
        self.assertIn("Статус: успешно", rendered)
        self.assertEqual(applied, [["77.88.8.8", "77.88.8.1"]])

    def test_tui_network_menu_displays_dns_option(self) -> None:
        from lucx_post_configurator.models import default_manifest
        from lucx_post_configurator.transaction import STATE_PATH
        with tempfile.TemporaryDirectory() as tempdir:
            fs = TargetFS(tempdir)
            state_file = fs.path(STATE_PATH)
            state_file.parent.mkdir(parents=True, exist_ok=True)
            import json
            manifest = default_manifest()
            manifest["dns"]["servers"] = ["1.1.1.1", "8.8.8.8"]
            state_file.write_text(
                json.dumps({"manifest": manifest}),
                encoding="utf-8",
            )
            engine = SimpleNamespace(fs=fs)
            inputs = iter(["0"])
            output: list[str] = []

            _network_menu(
                engine,  # type: ignore[arg-type]
                input_fn=lambda _prompt: next(inputs),
                output_fn=output.append,
            )

            rendered = "\n".join(output)
            self.assertIn("DNS: 1.1.1.1, 8.8.8.8", rendered)
            self.assertIn("1. Смена системного DNS (с замером пинга/задержки)", rendered)


    @mock.patch("lucx_post_configurator.dns_manager.verify_dns_resolution", return_value=True)
    @mock.patch("lucx_post_configurator.dns_manager.probe_dns_server", return_value=5.0)
    def test_run_dns_security_diagnostic(self, mock_probe, mock_verify) -> None:
        from lucx_post_configurator.dns_manager import run_dns_security_diagnostic
        with tempfile.TemporaryDirectory() as tempdir:
            fs = TargetFS(tempdir)
            runner = Runner(dry_run=True)
            diag = run_dns_security_diagnostic(fs, runner)
            self.assertIn("resolver", diag)
            self.assertIn("servers", diag)
            self.assertIn("resolution_checks", diag)
            self.assertIn("port_isolation", diag)


if __name__ == "__main__":
    unittest.main()
