from __future__ import annotations

import dataclasses
import hashlib
import ipaddress
import re
import shlex
from pathlib import PurePosixPath
from typing import Any

from .models import valid_domain


class NaiveFrontendError(ValueError):
    pass


@dataclasses.dataclass(slots=True)
class NaiveSource:
    auth_pairs: list[tuple[str, str]] = dataclasses.field(default_factory=list)
    hide_ip: bool = False
    hide_via: bool = False
    probe_resistance: bool = False
    upstream: str = ""
    source_sha256: str = ""


def _tokens(raw: str) -> list[str]:
    try:
        return shlex.split(raw, comments=True, posix=True)
    except ValueError as exc:
        raise NaiveFrontendError(f"cannot parse Caddyfile line: {exc}") from exc


def parse_naive_caddyfile(text: str) -> NaiveSource:
    """Parse only the bounded line-oriented structure generated by LucX."""

    if not isinstance(text, str) or not text.strip() or len(text.encode("utf-8")) > 1024 * 1024:
        raise NaiveFrontendError("Naive Caddyfile is empty or exceeds the safe parser limit")
    result = NaiveSource(source_sha256=hashlib.sha256(text.encode("utf-8")).hexdigest())
    stack: list[str] = []
    forward_blocks = 0

    for line_number, raw in enumerate(text.splitlines(), start=1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        tokens = _tokens(raw)
        if not tokens:
            continue
        if tokens == ["}"]:
            if not stack:
                raise NaiveFrontendError(f"unbalanced closing brace on line {line_number}")
            stack.pop()
            continue

        opens = tokens[-1] == "{"
        if opens:
            head = tokens[0]
            parent = stack[-1] if stack else ""
            if tokens == ["{"]:
                context = "global"
                if stack:
                    raise NaiveFrontendError(f"unexpected global block on line {line_number}")
            elif not stack:
                context = "site"
            elif head == "log" and parent in {"global", "site"}:
                context = "log"
            elif head == "servers" and parent == "global":
                context = "servers"
            elif head == "route" and parent == "site":
                context = "route"
            elif head == "forward_proxy" and parent == "route":
                context = "forward_proxy"
                forward_blocks += 1
            else:
                raise NaiveFrontendError(f"unsupported block {head!r} on line {line_number}")
            stack.append(context)
            continue

        if "{" in tokens or "}" in tokens:
            raise NaiveFrontendError(f"inline braces are not accepted on line {line_number}")
        context = stack[-1] if stack else ""
        directive = tokens[0]
        if context == "global":
            allowed = {"admin", "skip_install_trust", "auto_https"}
            if directive not in allowed:
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "site":
            if directive not in {"bind", "tls"}:
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "log":
            if directive not in {"level", "output", "format"}:
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "servers":
            if directive != "protocols":
                raise NaiveFrontendError(f"unsupported directive {directive!r} on line {line_number}")
        elif context == "forward_proxy":
            if directive == "basic_auth" and len(tokens) == 3:
                result.auth_pairs.append((tokens[1], tokens[2]))
            elif directive == "hide_ip" and len(tokens) == 1:
                result.hide_ip = True
            elif directive == "hide_via" and len(tokens) == 1:
                result.hide_via = True
            elif directive == "probe_resistance" and len(tokens) == 1:
                result.probe_resistance = True
            elif directive == "upstream" and len(tokens) == 2 and not result.upstream:
                result.upstream = tokens[1]
            else:
                raise NaiveFrontendError(
                    f"unsupported forward_proxy directive {directive!r} on line {line_number}"
                )
        else:
            raise NaiveFrontendError(f"directive {directive!r} is outside an allowed block")

    if stack:
        raise NaiveFrontendError("Naive Caddyfile has unclosed blocks")
    if forward_blocks != 1:
        raise NaiveFrontendError("Naive Caddyfile must contain exactly one forward_proxy block")
    if not result.auth_pairs:
        raise NaiveFrontendError("Naive forward_proxy has no basic_auth entries")
    return result


_CONNECT_SOURCE_ERROR = 'Источник Naive не подтверждён'


def _line_tokens(line: str) -> list[str]:
    """Ограниченная однострочная лексика Caddy 2.11.2, без shell semantics.

    Только двойная кавычка и backtick в начале токена открывают quoting.
    В двойных кавычках backslash снимается лишь перед двойной кавычкой.
    Heredoc, переносы и подстановки окружения не входят в этот adapter.
    """
    tokens, index = [], 0
    while index < len(line):
        if line[index].isspace():
            index += 1
            continue
        if line[index] == '#':
            break
        quote = line[index] if line[index] in {'"', '`'} else ''
        if quote:
            index += 1
            value = []
            while index < len(line) and line[index] != quote:
                character = line[index]
                if quote == '"' and character == '\\':
                    if index + 1 >= len(line):
                        raise ValueError(_CONNECT_SOURCE_ERROR)
                    following = line[index + 1]
                    value.extend([following] if following == '"' else [character, following])
                    index += 2
                else:
                    value.append(character)
                    index += 1
            if index >= len(line):
                raise ValueError(_CONNECT_SOURCE_ERROR)
            index += 1
            if index < len(line) and not line[index].isspace():
                raise ValueError(_CONNECT_SOURCE_ERROR)
            tokens.append(''.join(value))
        else:
            start = index
            while index < len(line) and not line[index].isspace():
                index += 1
            value = line[start:index]
            if value.startswith(('\\', '<<')) or value.endswith('\\') or '\\<' in value:
                raise ValueError(_CONNECT_SOURCE_ERROR)
            tokens.append(value)
    return tokens


def parse_naive_connect_source(text: str) -> NaiveSource:
    """Чистый bounded Caddy parser; ограничения профиля остаются у вызывающего."""
    if (not isinstance(text, str) or not text.strip()
            or len(text.encode("utf-8")) > 1024 * 1024):
        raise ValueError(_CONNECT_SOURCE_ERROR)
    if ('{$' in text or '{env.' in text or '\r' in text.replace('\r\n', '') or '\ufeff' in text
            or any(ord(character) < 32 and character not in '\r\n\t' for character in text)):
        raise ValueError(_CONNECT_SOURCE_ERROR)
    # Только внутренний мост к существующей проверке структуры: полученные
    # Caddy tokens кодируются для shlex без потери значений. Это не Caddyfile
    # для запуска/записи и не shell command.
    lines = []
    for line in text.split('\n'):
        tokens = _line_tokens(line.rstrip('\r'))
        if tokens and tokens[0] == 'basic_auth' and any('{' in item or '}' in item for item in tokens[1:]):
            raise ValueError(_CONNECT_SOURCE_ERROR)
        lines.append(shlex.join(tokens))
    return parse_naive_caddyfile('\n'.join(lines))


@dataclasses.dataclass(frozen=True, slots=True, repr=False)
class NaiveNativeSource:
    """Форма текущего исходника; не доказательство загрузки активным процессом."""

    port: int
    bind_host: str
    server_names: tuple[str, ...]
    cert_path: str
    key_path: str
    probe_resistance: bool
    source_sha256: str
    upstream_sha256: str


def parse_naive_native_source(text: str) -> NaiveNativeSource:
    """Только каноническая manual-TLS цепочка LucX, без чтения файлов/секретов TLS.

    Отсутствие servers использует defaults закреплённого Caddy, включающие h2.
    Вызывающий код отдельно доказывает binary, endpoint, source freshness и обмен.
    ACME и прочие формы здесь пока не подтверждаются.
    """
    try:
        source = parse_naive_connect_source(text)
        if (not source.hide_ip or not source.hide_via or not 1 <= len(source.auth_pairs) <= 128
                or len({user for user, _ in source.auth_pairs}) != len(source.auth_pairs)
                or any(not value or len(value.encode('utf-8')) > 1024
                       for pair in source.auth_pairs for value in pair)):
            raise ValueError
        lines = text.splitlines()
        if len(lines) > 4096:
            raise ValueError
        tree: list = []
        stack = [tree]
        for line in lines:
            tokens = _line_tokens(line)
            if not tokens:
                continue
            if tokens == ['}']:
                if len(stack) == 1:
                    raise ValueError
                stack.pop()
            elif tokens[-1] == '{':
                children: list = []
                stack[-1].append((tuple(tokens[:-1]), children))
                stack.append(children)
                if len(stack) > 5:
                    raise ValueError
            else:
                stack[-1].append((tuple(tokens), None))
        if len(stack) != 1 or len(tree) != 2 or tree[0][0] != ():
            raise ValueError

        def directives(nodes, allowed):
            if nodes is None:
                raise ValueError
            result = {}
            for head, children in nodes:
                if not head or head[0] not in allowed or head[0] in result:
                    raise ValueError
                result[head[0]] = (head[1:], children)
            return result

        def path(value):
            parsed = PurePosixPath(value)
            if (not parsed.is_absolute() or '..' in parsed.parts or value.startswith('//')
                    or str(parsed) != value
                    or any(c in value for c in '{}') or len(value.encode('utf-8')) > 4096):
                raise ValueError
            return value

        glob = directives(tree[0][1], {'admin', 'auto_https', 'skip_install_trust', 'log', 'servers'})
        if glob.get('admin') != (('off',), None) or glob.get('auto_https') != (('off',), None):
            raise ValueError
        if 'skip_install_trust' in glob and glob['skip_install_trust'] != ((), None):
            raise ValueError
        if 'log' in glob:
            args, children = glob['log']
            logs = directives(children, {'level'})
            if (args or set(logs) != {'level'} or logs['level'][1] is not None
                    or logs['level'][0] not in {(level,) for level in ('DEBUG', 'INFO', 'WARN', 'ERROR', 'FATAL', 'PANIC')}):
                raise ValueError
        if 'servers' in glob:
            args, children = glob['servers']
            if args or directives(children, {'protocols'}) != {'protocols': (('h1', 'h2'), None)}:
                raise ValueError
        labels = ' '.join(tree[1][0]).split(', ')
        if not 1 <= len(labels) <= 2 or not re.fullmatch(r':[1-9][0-9]{0,4}', labels[0]):
            raise ValueError
        port = int(labels[0][1:])
        if port > 65535:
            raise ValueError
        names = ()
        if len(labels) == 2:
            authority = labels[1]
            suffix = ':' + str(port)
            name = authority[:-len(suffix)] if authority.endswith(suffix) else authority if port == 443 else ''
            if not name or not valid_domain(name) or '*' in name or name != name.lower().rstrip('.'):
                raise ValueError
            names = (name,)
        site = directives(tree[1][1], {'bind', 'tls', 'log', 'route'})
        if not {'tls', 'route'} <= site.keys():
            raise ValueError
        tls_args, tls_children = site['tls']
        if tls_children is not None or len(tls_args) != 2:
            raise ValueError
        cert, key = (path(value) for value in tls_args)
        if cert == key:
            raise ValueError
        bind = ''
        if 'bind' in site:
            args, children = site['bind']
            if children is not None or len(args) != 1 or '%' in args[0]:
                raise ValueError
            bind = str(ipaddress.ip_address(args[0]))
        if 'log' in site:
            args, children = site['log']
            logs = directives(children, {'output', 'format'})
            if (args or set(logs) != {'output', 'format'} or logs['format'] != (('json',), None)
                    or logs['output'][1] is not None or len(logs['output'][0]) != 2
                    or logs['output'][0][0] != 'file'):
                raise ValueError
            if path(logs['output'][0][1]) in {cert, key}:
                raise ValueError
        args, children = site['route']
        routes = directives(children, {'forward_proxy'})
        if args or set(routes) != {'forward_proxy'} or routes['forward_proxy'][0]:
            raise ValueError
        forward = routes['forward_proxy'][1]
        if forward is None or any(children is not None for _, children in forward):
            raise ValueError
        flags = [head[0] for head, _ in forward if head[0] != 'basic_auth']
        if len(set(flags)) != len(flags):
            raise ValueError
        upstream = source.upstream
        if upstream:
            match = re.fullmatch(r'socks5://lucx:[A-Za-z0-9_-]{24}@127\.0\.0\.1:([1-9][0-9]{0,4})', upstream)
            if match is None or int(match[1]) > 65535:
                raise ValueError
        return NaiveNativeSource(port, bind, names, cert, key, source.probe_resistance,
            hashlib.sha256(text.encode('utf-8')).hexdigest(),
            hashlib.sha256(upstream.encode('utf-8')).hexdigest() if upstream else '')
    except (ValueError, TypeError, IndexError, KeyError, AttributeError):
        raise ValueError(_CONNECT_SOURCE_ERROR) from None


def _top_level_blocks(text: str) -> list[tuple[str, str]]:
    blocks: list[tuple[str, str]] = []
    depth = 0
    start = 0
    prefix_start = 0
    quote = ""
    escaped = False
    for index, character in enumerate(text):
        if escaped:
            escaped = False
            continue
        if character == "\\" and quote:
            escaped = True
            continue
        if character in {'"', "'"}:
            if quote == character:
                quote = ""
            elif not quote:
                quote = character
            continue
        if quote:
            continue
        if character == "{":
            if depth == 0:
                prefix = text[prefix_start:index].strip()
                start = index + 1
            depth += 1
        elif character == "}":
            depth -= 1
            if depth < 0:
                return []
            if depth == 0:
                blocks.append((prefix, text[start:index]))
                prefix_start = index + 1
    return blocks if depth == 0 else []


def supports_native_decoy(text: str) -> bool:
    for prefix, body in _top_level_blocks(text):
        if not prefix:
            continue
        has_proxy = bool(re.search(r"(?:^|[{}\n])\s*forward_proxy\s*\{", body))
        has_files = bool(re.search(r"(?:^|[{}\n])\s*file_server(?:\s|$)", body))
        if has_proxy and has_files:
            return True
    return False


def _caddy_quote(value: Any) -> str:
    text = str(value)
    if any(character in text for character in ("\x00", "\r", "\n")):
        raise NaiveFrontendError("newline or NUL in Caddy token")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_managed_naive_caddyfile(
    source: NaiveSource,
    *,
    domain: str,
    listen_port: int,
    cert_path: str,
    key_path: str,
    site_root: str,
) -> str:
    domain = str(domain).strip().lower().rstrip(".")
    if not valid_domain(domain) or not 1 <= int(listen_port) <= 65535:
        raise NaiveFrontendError("invalid managed Naive domain or listener port")
    for path in (cert_path, key_path, site_root):
        if not str(path).startswith("/"):
            raise NaiveFrontendError("managed Naive paths must be absolute")
    lines = [
        "{",
        "    admin off",
        "    skip_install_trust",
        "    auto_https off",
        "    servers {",
        "        protocols h1 h2",
        "    }",
        "}",
        "",
        f":{int(listen_port)}, {_caddy_quote(domain + ':' + str(int(listen_port)))} {{",
        "    bind 127.0.0.1",
        f"    tls {_caddy_quote(cert_path)} {_caddy_quote(key_path)}",
        "    route {",
        "        @browser method GET HEAD",
        "        handle @browser {",
        f"            header X-LucX-Decoy {_caddy_quote(domain)}",
        f"            root * {_caddy_quote(site_root)}",
        "            file_server",
        "        }",
        "        forward_proxy {",
    ]
    for user, password in source.auth_pairs:
        lines.append(f"            basic_auth {_caddy_quote(user)} {_caddy_quote(password)}")
    if source.hide_ip:
        lines.append("            hide_ip")
    if source.hide_via:
        lines.append("            hide_via")
    if source.probe_resistance:
        lines.append("            probe_resistance")
    if source.upstream:
        lines.append(f"            upstream {_caddy_quote(source.upstream)}")
    lines.extend(["        }", "    }", "}"])
    return "\n".join(lines) + "\n"


def render_naive_frontend_unit(*, inbound_id: int, binary_path: str) -> str:
    if int(inbound_id) <= 0 or not str(binary_path).startswith("/"):
        raise NaiveFrontendError("invalid Naive unit identity or binary path")
    config = f"/etc/lucx-post-configurator/naive/naive-{int(inbound_id)}.caddyfile"
    state_name = f"lucx-naive-decoy-{int(inbound_id)}"
    data = f"/var/lib/{state_name}"
    return f"""[Unit]
Description=LucX managed Naive browser frontend for inbound {int(inbound_id)}
After=network.target x-ui.service
PartOf=x-ui.service

[Service]
Type=simple
User=root
Group=root
UMask=0077
Environment=XDG_DATA_HOME={data}
Environment=HOME={data}
Environment=XDG_CONFIG_HOME={data}/config
StateDirectory={state_name}
StateDirectoryMode=0700
ExecStart={binary_path} run --config {config} --adapter caddyfile
Restart=on-failure
RestartSec=2s
NoNewPrivileges=yes
PrivateTmp=yes
PrivateDevices=yes
ProtectSystem=strict
ProtectHome=read-only
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
LockPersonality=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX

[Install]
WantedBy=multi-user.target
"""


def frontend_sync_state(expected_sha256: str, current_sha256: str) -> str:
    if not re.fullmatch(r"[0-9a-f]{64}", str(expected_sha256 or ""), re.IGNORECASE):
        return "blocked"
    if not re.fullmatch(r"[0-9a-f]{64}", str(current_sha256 or ""), re.IGNORECASE):
        return "blocked"
    return "ready" if expected_sha256.lower() == current_sha256.lower() else "needs_sync"


def render_naive_sync_script() -> str:
    return """#!/usr/bin/env python3
import os, re, stat, subprocess, sys

COMMAND = "/usr/local/sbin/lucx-post-configure"


def failure():
    sys.stderr.write("[lucx-naive-sync] Синхронизация не выполнена.\\n")
    return 1


def main(args):
    if len(args) != 1 or not re.fullmatch(r"[1-9][0-9]{0,9}", args[0]):
        return failure()
    if int(args[0]) > 2147483647:
        return failure()
    try:
        metadata = os.lstat(COMMAND)
        if (not stat.S_ISREG(metadata.st_mode) or metadata.st_uid != 0
                or metadata.st_mode & 0o022 or not metadata.st_mode & stat.S_IXUSR):
            return failure()
        # Общая транзакция Engine владеет lock, валидацией и receipt/rollback.
        # Не прерываем её таймером посредника во время commit.
        result = subprocess.run(
            [COMMAND, "--sync-naive-inbound", args[0]],
            stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            env={"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                 "LANG": "C.UTF-8", "LC_ALL": "C.UTF-8"}, check=False,
        )
        return 0 if result.returncode == 0 else failure()
    except OSError:
        return failure()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
"""


def render_naive_sync_path(inbound_id: int) -> str:
    return f"""[Unit]
Description=Watch LucX Naive Caddyfile for inbound {int(inbound_id)}
After=network.target x-ui.service

[Path]
PathModified=/usr/local/x-ui/bin/tunnel/naive-{int(inbound_id)}.caddyfile
Unit=lucx-naive-sync-{int(inbound_id)}.service

[Install]
WantedBy=multi-user.target
"""


def render_naive_sync_unit(inbound_id: int) -> str:
    return f"""[Unit]
Description=Sync LucX Naive credentials for inbound {int(inbound_id)}
After=x-ui.service

[Service]
Type=oneshot
User=root
Group=root
UMask=0077
TimeoutStartSec=0
ExecStart=/usr/local/libexec/lucx-naive-sync.py {int(inbound_id)}
"""
